services:
  - type: web
    name: icecreamshop
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn IceCreamShop.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: icecream-db
          property: connectionString

databases:
  - name: icecream-db
    databaseName: icecream
    user: icecream_user 
