services:
  - type: web
    name: icecreamshop
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn IceCreamShop.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: icecream-db
    databaseName: icecream
    user: icecream_user 
