# Generated by Django 5.1.5 on 2025-03-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_icecreamflavor_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
    ]
